% This function mxMSCreateContext, connects to the Microsoft Kinect-hardware,
% and initializes objects  such as image, IR and Depth streams.
%
% KinectHandles = mxMSCreateContext(R);
%
% inputs, 
%   (optional)
%       R : 1 x 2 array with resolution of image stream and depth stream
%           defaults to [2 1]
%       	0 : 80x60, 1:320x240, 2:640x480, 3:1280x1024
%            
% outputs,
%   KinectHandles : Array with pointers to kinect node objects generated by
%          mxMSCreateContext, such as image and Depth nodes
%
% Note, 
%   You always have to close the Kinect-Hardware Connection and remove
%   the Kinect Objects after usage. By running DeleteContext(KinectHandles);
%
%
% See also mxMSDepth, mxMSPhoto, mxMSSkeleton, mxMSDeleteContext, 
%       compile_cpp_files
%
% Mex-Wrapper is written by D.Kroon University of Twente (September 2011)  
