% This function mxMSSkeleton does (multiple) user-detection followed by
% user tracking on a kinect-stream
%
% P = mxMSSkeleton(KinectHandles);
%
% inputs
%   KinectHandles : Array with pointers to kinect node objects generated by
%          mxMSCreateContext, such as main, image, IR, Depth and User node.
%   P : An array with size 200 x 6
%       The columes are
%        1 : UserID 
%        2,3,4 : X,Y,Z coordinates 
%        5,6 : X,Y coordinates in the depth image
%       The rows are the following:
%          HIP CENTER,     SPINE,       SHOULDER CENTER, HEAD,
%          SHOULDER LEFT,  ELBOW LEFT,  WRIST LEFT,      HAND LEFT,
%          SHOULDER RIGHT, ELBOW RIGHT, WRIST RIGHT,     HAND RIGHT,
%          HIP LEFT,       KNEE LEFT,   ANKLE LEFT,      FOOT LEFT,
%          HIP RIGHT,      KNEE RIGHT,  ANKLE RIGHT,     FOOT RIGHT
%       The first user data is P(1:20,:), for the second user the
%       data stored P(21:40,:), for the third P(41:60) ...
%
%
% See also mxMSCreateContext, mxMSDepth, mxMSPhoto,
%		mxMSDeleteContext
%
% Mex-Wrapper is written by D.Kroon University of Twente (September 2011)  