% This function mxMSDepth, takes the Current-Depth (movie) frame from 
%   the Kinect-Stream, and makes it available as matlab variable
%
% 	D = mxMSDepth(KinectHandles);
%
% inputs,
%   KinectHandles : Array with pointers to kinect node objects generated by
%          mxMSCreateContext, such as main, image, IR, Depth and User node.
%
% outputs,
%   D : A 2D Matrix of type Uint16 with Depth information. 
%       This depth is not in world-coordinates, if you want
%       World-coordinates use mxMSDepthRealWorld.
%
% note : When tracking a player, the first 2bits of the depth pixels 
%	 of the player, are set to his id.
%
% See also mxMSCreateContext,  mxMSPhoto, mxMSSkeleton, mxMSDeleteContext
%
% Mex-Wrapper is written by D.Kroon University of Twente (September 2011)  
